<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <AssemblyName>Chips.Runtime</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;CS8618</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;CS8618</NoWarn>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="AsmResolver.DotNet" Version="5.5.1" />
    <PackageReference Include="Sprache" Version="2.3.1" />
    <PackageReference Include="DecimalMath.DecimalEx" Version="1.0.2" />
    <PackageReference Include="System.CodeDom" Version="8.0.0" />
  </ItemGroup>
  
  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Chips.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Meta\Arithmetic.Generated.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Arithmetic.Generated.tt</DependentUpon>
    </None>
    <None Include="Meta\Status.Generated.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Status.Generated.tt</DependentUpon>
    </None>
    <None Include="Utility\Arithmetic.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Arithmetic.tt</DependentUpon>
    </None>
    <None Include="Utility\ValueConverter.Casting.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ValueConverter.Casting.tt</DependentUpon>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Meta\Arithmetic.Generated.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Arithmetic.Generated.tt</DependentUpon>
    </Compile>
    <Compile Update="Meta\Status.Generated.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Status.Generated.tt</DependentUpon>
    </Compile>
    <Compile Update="Utility\Arithmetic.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Arithmetic.tt</DependentUpon>
    </Compile>
    <Compile Update="Utility\ConstrainedArithmetic.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ConstrainedArithmetic.tt</DependentUpon>
    </Compile>
    <Compile Update="Utility\OverflowDetectionArithmetic.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>OverflowDetectionArithmetic.tt</DependentUpon>
    </Compile>
    <Compile Update="Utility\ValueConverter.Casting.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ValueConverter.Casting.tt</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Meta\Arithmetic.Generated.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Arithmetic.Generated.cs</LastGenOutput>
    </None>
    <None Update="Meta\Status.Generated.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Status.Generated.cs</LastGenOutput>
    </None>
    <None Update="Utility\Arithmetic.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Arithmetic.cs</LastGenOutput>
    </None>
    <None Update="Utility\ValueConverter.Casting.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>ValueConverter.Casting.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>